#ifndef COMMAND_PATTERN_ACNOTAVAILABLEEXCEPTION_H
#define COMMAND_PATTERN_ACNOTAVAILABLEEXCEPTION_H

#include <exception>

class ACNoteAvailableException : public std::exception {};

#endif //COMMAND_PATTERN_ACNOTAVAILABLEEXCEPTION_H
