#ifndef ICONS_H
#define ICONS_H

#define QT_ICON (QIcon{ ":/icons/qt.svg" })

#define VISIBILITYOFF_ICON_LIGHT (QIcon(":/icons/light/visibility_off_white_24dp.svg"))
#define CHECK_ICON_LIGHT (QIcon(":/icons/light/check_circle_outline_white_24dp.svg"))
#define VISIBILITYON_ICON_LIGHT (QIcon(":/icons/light/visibility_white_24dp.svg"))
#define WARNING_ICON_LIGHT (QIcon(":/icons/light/warning_amber_white_24dp.svg"))
#define COPYRIGHT_ICON_LIGHT (QIcon(":/icons/light/copyright_white_24dp.svg"))
#define TRANSLATE_ICON_LIGHT (QIcon(":/icons/light/translate_white_24dp.svg"))
#define SHORTCUT_ICON_LIGHT (QIcon(":/icons/light/shortcut_white_24dp.svg"))
#define MINIMIZE_ICON_LIGHT (QIcon(":/icons/light/minimize_white_24dp.svg"))
#define COPY_ICON_LIGHT (QIcon(":/icons/light/content_copy_white_24dp.svg"))
#define HELP_ICON_LIGHT (QIcon(":/icons/light/help_outline_white_24dp.svg"))
#define OFF_ICON_LIGHT (QIcon(":/icons/light/highlight_off_white_24dp.svg"))
#define INFO_ICON_LIGHT (QIcon(":/icons/light/info_outline_white_24dp.svg"))
#define EXIT_ICON_LIGHT (QIcon(":/icons/light/exit_to_app_white_24dp.svg"))
#define APP_ICON_LIGHT (QIcon(":/icons/light/lock_outline_white_24dp.svg"))
#define PALETTE_ICON_LIGHT (QIcon(":/icons/light/palette_white_24dp.svg"))
#define REFRESH_ICON_LIGHT (QIcon(":/icons/light/refresh_white_24dp.svg"))
#define CUT_ICON_LIGHT (QIcon(":/icons/light/content_cut_white_24dp.svg"))
#define CLOSE_ICON_LIGHT (QIcon(":/icons/light/close_white_24dp.svg"))
#define MENU_ICON_LIGHT (QIcon(":/icons/light/menu_white_24dp.svg"))
#define DONE_ICON_LIGHT (QIcon(":/icons/light/done_white_24dp.svg"))

#define DONE_ICON_DARK (QIcon(":/icons/dark/done_black_24dp.svg"))
#define MENU_ICON_DARK (QIcon(":/icons/dark/menu_black_24dp.svg"))
#define CLOSE_ICON_DARK (QIcon(":/icons/dark/close_black_24dp.svg"))
#define CUT_ICON_DARK (QIcon(":/icons/dark/content_cut_black_24dp.svg"))
#define REFRESH_ICON_DARK (QIcon(":/icons/dark/refresh_black_24dp.svg"))
#define PALETTE_ICON_DARK (QIcon(":/icons/dark/palette_black_24dp.svg"))
#define EXIT_ICON_DARK (QIcon(":/icons/dark/exit_to_app_black_24dp.svg"))
#define APP_ICON_DARK (QIcon(":/icons/dark/lock_outline_black_24dp.svg"))
#define COPY_ICON_DARK (QIcon(":/icons/dark/content_copy_black_24dp.svg"))
#define HELP_ICON_DARK (QIcon(":/icons/dark/help_outline_black_24dp.svg"))
#define OFF_ICON_DARK (QIcon(":/icons/dark/highlight_off_black_24dp.svg"))
#define INFO_ICON_DARK (QIcon(":/icons/dark/info_outline_black_24dp.svg"))
#define MINIMIZE_ICON_DARK (QIcon(":/icons/dark/minimize_black_24dp.svg"))
#define SHORTCUT_ICON_DARK (QIcon(":/icons/dark/shortcut_black_24dp.svg"))
#define COPYRIGHT_ICON_DARK (QIcon(":/icons/dark/copyright_black_24dp.svg"))
#define TRANSLATE_ICON_DARK (QIcon(":/icons/dark/translate_black_24dp.svg"))
#define WARNING_ICON_DARK (QIcon(":/icons/dark/warning_amber_black_24dp.svg"))
#define VISIBILITYON_ICON_DARK (QIcon(":/icons/dark/visibility_black_24dp.svg"))
#define CHECK_ICON_DARK (QIcon(":/icons/dark/check_circle_outline_black_24dp.svg"))
#define VISIBILITYOFF_ICON_DARK (QIcon(":/icons/dark/visibility_off_black_24dp.svg"))

#endif
